# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84849f05a32d819be739b269f0c3c3bec76868630aff9c28004cb63645b3ff810a1aa090f435a81e403f5f9fad18d41d60ab1a67b4743b5607ef5c095a538a10

test:
  secret_key_base: 831cd004895f2f6e2fe540bc3f41c0cc3de1761abd29c6055544201ed834bebe9df1b15baa45c62647c3e18446f3252a190b50d326d3b0d452bcd12f24e81ec3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
